- hosts: prometheus
  #strategy: free
  become: yes
  roles: 
    - ntp
    - prometheus

- hosts: grafana
  become: yes
  roles: 
    - ntp
    - grafana

- hosts: alertmanager
  become: yes
  roles:
    - ntp
    - alertmanager

- hosts: all
  become: yes
  roles:
    - node_exporter

- hosts: kafka,zookeeper
  become: yes
  roles:
    - jmx_exporter
    
- hosts: kafka
  become: yes
  roles:
    - kafka_exporter
