- name: Create group nodeexporter
  group:
    name: nodeexporter
    state: present

- name: Create user nodeexporter
  user:
    name: nodeexporter
    shell: /sbin/nologin
    groups: [nodeexporter]
    append: yes

- name: Create nodeexporter folders
  file:
    path: "{{ item }}"
    owner: nodeexporter
    group: nodeexporter
    state: directory
    mode: '775'
  loop:
    - /tmp/nodeexporter

- name: Unarchive nodeexporter
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.0.0/node_exporter-1.0.0.linux-amd64.tar.gz
    dest: /tmp/nodeexporter
    remote_src: yes

- name: Get correct path
  find:
    paths: [/tmp/nodeexporter]
    file_type: directory
    recurse: no
  register: resultado_find

- name: Copy files to path
  copy:
    src: "{{ resultado_find.files[0].path }}/{{ item }}"
    dest: /usr/local/bin/
    remote_src: yes
    owner: nodeexporter
    group: nodeexporter
    mode: '775'
  loop:
    - node_exporter

- name: Copy nodeexporter init files
  copy: 
    src: node_exporter.service
    dest: /etc/systemd/system/
    owner: nodeexporter
    group: nodeexporter
    mode: '775'

- name: Start nodeexporter 
  systemd:
    state: restarted
    daemon_reload: yes
    name: node_exporter
    enabled: yes